// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAGhQH8cgOAXaiU1jVEVsy1fqy497UY6I',
    appId: '1:1055986506130:web:6235e208696ff2aaf4094b',
    messagingSenderId: '1055986506130',
    projectId: 'personal-notes-sahil',
    authDomain: 'personal-notes-sahil.firebaseapp.com',
    storageBucket: 'personal-notes-sahil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90NqZ62roSxzuXvDUptNMMvShawmpqRY',
    appId: '1:1055986506130:android:e23591da901caa6df4094b',
    messagingSenderId: '1055986506130',
    projectId: 'personal-notes-sahil',
    storageBucket: 'personal-notes-sahil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXMMRU15s7XeuHtv3pv3qO7rttDR89g0',
    appId: '1:1055986506130:ios:a06d174324d5dd41f4094b',
    messagingSenderId: '1055986506130',
    projectId: 'personal-notes-sahil',
    storageBucket: 'personal-notes-sahil.appspot.com',
    iosClientId: '1055986506130-vvdtaonm478td29n0h23qo5steg4fhk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
